### ISSUE TITLE
Rar decoder version 29 panic

### ISSUE THREAD

**Issue by bill-rich** [nwaples/rardecode#30]
This came up using trufflehog to scan a large number of repositories. I'm not sure of the file that caused this panic. I also haven't been able to reproduce the issue. If I can reproduce the issue in the future, I'll provide an example file.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xb424e4]

goroutine 1185589 [running]:
github.com/nwaples/rardecode/v2.(*rarBitReader).readBits(0xc0018af8b0, 0x10)
	github.com/nwaples/rardecode/v2@v2.0.0-beta.2/bit_reader.go:163 +0x44
github.com/nwaples/rardecode/v2.(*rarBitReader).readUint32(0x100c0018af828?)
	github.com/nwaples/rardecode/v2@v2.0.0-beta.2/bit_reader.go:209 +0xc5
github.com/nwaples/rardecode/v2.(*decoder29).parseVMFilter(0xc0082a33e0, {0xc04c695a08?, 0x20301f?, 0x20301f?})
	github.com/nwaples/rardecode/v2@v2.0.0-beta.2/decode29.go:118 +0x168
github.com/nwaples/rardecode/v2.(*decoder29).fill(0xc0082a33e0, 0xc000bead00)
	github.com/nwaples/rardecode/v2@v2.0.0-beta.2/decode29.go:246 +0xbd
github.com/nwaples/rardecode/v2.(*decodeReader).fill(0xc000bead00)
	github.com/nwaples/rardecode/v2@v2.0.0-beta.2/decode_reader.go:188 +0x8b
github.com/nwaples/rardecode/v2.(*decodeReader).bytes(0xc000bead00)
	github.com/nwaples/rardecode/v2@v2.0.0-beta.2/decode_reader.go:255 +0x32
github.com/nwaples/rardecode/v2.(*decodeReader).Read(0xc000bead00, {0xc049079000, 0x200, 0xb51025?})
	github.com/nwaples/rardecode/v2@v2.0.0-beta.2/decode_reader.go:301 +0x47
github.com/nwaples/rardecode/v2.(*limitedReader).Read(0xc07e72e420, {0xc049079000?, 0x7a543ee900000003?, 0xc07bd598c0?})
	github.com/nwaples/rardecode/v2@v2.0.0-beta.2/reader.go:260 +0x4a
github.com/nwaples/rardecode/v2.(*checksumReader).Read(0xc07e72e450, {0xc049079000, 0xc049079000?, 0x200})
	github.com/nwaples/rardecode/v2@v2.0.0-beta.2/reader.go:306 +0x37
github.com/nwaples/rardecode/v2.(*Reader).Read(0xc07b2fa480?, {0xc049079000?, 0x200?, 0x200?})
	github.com/nwaples/rardecode/v2@v2.0.0-beta.2/reader.go:346 +0x5e
github.com/trufflesecurity/trufflehog/v3/pkg/handlers.(*Archive).ReadToMax(0xc04c695950, {0x7fe559814a98, 0xc04c6b7c90})
	github.com/trufflesecurity/trufflehog/v3@v3.10.4-0.20220915124709-c4492b1fdc01/pkg/handlers/archive.go:144 +0x11c
github.com/trufflesecurity/trufflehog/v3/pkg/handlers.(*Archive).extractorHandler.func1({0x232b6c8, 0xc07e72e300}, {{0x232fd88, 0xc07bd59940}, {0x1a45660, 0xc07bd59940}, {0xc0075c47b0, 0x24}, {0x0, 0x0}, ...})
	github.com/trufflesecurity/trufflehog/v3@v3.10.4-0.20220915124709-c4492b1fdc01/pkg/handlers/archive.go:124 +0x13d
github.com/mholt/archiver/v4.Rar.Extract({0xc7?, {0x0?, 0x1bbf460?}}, {0x232b6c8, 0xc07e72e300}, {0x230fee0?, 0xc07dc09bf0?}, {0x0, 0x0, 0x0}, ...)
	github.com/mholt/archiver/v4@v4.0.0-alpha.7/rar.go:108 +0x45d
github.com/trufflesecurity/trufflehog/v3/pkg/handlers.(*Archive).openArchive(0xc00a7d5710?, {0x232b658, 0xc000128000}, 0x0, {0x230fee0?, 0xc07dc09bf0?}, 0xc0048b9620?)
	github.com/trufflesecurity/trufflehog/v3@v3.10.4-0.20220915124709-c4492b1fdc01/pkg/handlers/archive.go:76 +0x18c
github.com/trufflesecurity/trufflehog/v3/pkg/handlers.(*Archive).FromFile.func1()
	github.com/trufflesecurity/trufflehog/v3@v3.10.4-0.20220915124709-c4492b1fdc01/pkg/handlers/archive.go:42 +0x6e
created by github.com/trufflesecurity/trufflehog/v3/pkg/handlers.(*Archive).FromFile
	github.com/trufflesecurity/trufflehog/v3@v3.10.4-0.20220915124709-c4492b1fdc01/pkg/handlers/archive.go:40 +0xfb
```

**Comment by nwaples** [comment]
Sorry for the delay, should be fixed with the latest commit.
